name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request(merge request in Gitllab) events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone Project 
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run script 1 
        run: echo script -1 
      # Runs a set of commands using the runners shell
      - name: Run script 2 
        run: |
          echo script 2.1 of job 1
          echo script 2.2 of job 1

  job-2:
    
    runs-on: ubuntu-latest

    #needs: [job-1] # wait for job-1 to finsih after that begin with job-2 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone Project 
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run script 2 
        run: echo script -2 
      # Runs a set of commands using the runners shell
      - name: Run script 2 
        run: |
          echo script 2.1 of job 2
          echo script 2.2 of job 2 
